<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2qu1eya\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2qu1eya/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2qu1eya.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2qu1eya\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container2qu1eya\srcDevDebugProjectContainer(array(
    'container.build_hash' => '2qu1eya',
    'container.build_id' => '77720f04',
    'container.build_time' => 1531470878,
), __DIR__.\DIRECTORY_SEPARATOR.'Container2qu1eya');
